import type { Metadata } from "next";
import { K2D } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

import { BreadcrumbsProvider } from "@/context/BreadcrumbsContext";
import { Suspense } from "react";
import BreadcrumbsDataLoader from "@/components/BreadcrumbsDataLoader";

const k2d = K2D({
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${k2d.className} flex min-h-screen flex-col bg-background antialiased`}
      >
        <Header />
        <main className="grow">
          <BreadcrumbsProvider>
            <Suspense>
              <BreadcrumbsDataLoader />
            </Suspense>
            {children}
          </BreadcrumbsProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
